/*

 BKG_SC_C1.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : background_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_score_w_card1Width 4
#define bkg_score_w_card1Height 5
#define bkg_score_w_card1Bank 0

const unsigned char bkg_score_w_card1[] =
{
  0x25,0x25,0x25,0x38,0x25,0x25,0x25,0x01,0x25,0x00,
  0x00,0x01,0x25,0x25,0x25,0x01,0x25,0x25,0x25,0x02
};

/* End of BKG_SC_C1.C */
