/*

 BKG_WIN_CASH_BET.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 1
   Tile set      : background_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_cash_betWidth 20
#define bkg_cash_betHeight 1
#define bkg_cash_betBank 0

unsigned char bkg_cash_bet[] =
{
  0x00,0x42,0x43,0x6D,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
  0x44,0x45,0x6D,0x00,0x00,0x00,0x00,
};

/* End of BKG_WIN_CASH_BET.C */
