/*

 BKG_SHUF.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 3
   Tile set      : C:\Users\alexa\OneDrive\Desktop\C Files\GB\blackjack_gb_game\res_\gbr_files\bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_shuffleWidth 11
#define bkg_shuffleHeight 3
#define bkg_shuffleBank 0

const unsigned char bkg_shuffle[] =
{
  0x5A,0x5D,0x5D,0x5D,0x5D,0x5D,0x5D,0x5D,0x5D,0x5D,
  0x5F,0x5B,0x1C,0x11,0x1E,0x0F,0x0F,0x15,0x12,0x17,
  0x10,0x60,0x5C,0x5E,0x5E,0x5E,0x5E,0x5E,0x5E,0x5E,
  0x5E,0x5E,0x61
};

/* End of BKG_SHUF.C */
