/*

 BKG_LOSE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 3
   Tile set      : C:\Users\alexa\OneDrive\Desktop\C Files\GB\blackjack_gb_game\res_\gbr_files\bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bkg_lose_h_INCLUDE
#define __bkg_lose_h_INCLUDE

#define bkg_loserWidth 10
#define bkg_loserHeight 3
#define bkg_loserBank 0

extern const unsigned char bkg_loser[];

#endif

/* End of BKG_LOSE.H */
