/*

 CASH_WINDOW.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 14 x 1
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_cash_betWidth 14
#define bkg_cash_betHeight 1
#define bkg_cash_betBank 0

const unsigned char bkg_cash_bet[] =
{
  0x29,0x2A,0x28,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,0x2F,
  0x2F,0x2B,0x2C,0x28
};

/* End of CASH_WINDOW.C */
