/*

 BKG_SHUF.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 3
   Tile set      : background_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bkg_shuf_h_INCLUDE
#define __bkg_shuf_h_INCLUDE

#define bkg_shuffleWidth 11
#define bkg_shuffleHeight 3
#define bkg_shuffleBank 0

extern const unsigned char bkg_shuffle[];

#endif

/* End of BKG_SHUF.H */
