/*

 BKG_WIN.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 3
   Tile set      : C:\Users\alexa\OneDrive\Desktop\C Files\GB\blackjack_gb_game\res_\gbr_files\bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_winnerWidth 10
#define bkg_winnerHeight 3
#define bkg_winnerBank 0

const unsigned char bkg_winner[] =
{
  0x5A,0x5D,0x5D,0x5D,0x5D,0x5D,0x5D,0x5D,0x5D,0x5F,
  0x5B,0x22,0x18,0x1E,0x2F,0x20,0x12,0x17,0x26,0x60,
  0x5C,0x5E,0x5E,0x5E,0x5E,0x5E,0x5E,0x5E,0x5E,0x61
};

/* End of BKG_WIN.C */
