/*

 BKG_HS_OPT.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 2
   Tile set      : background_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_hs_oWidth 5
#define bkg_hs_oHeight 2
#define bkg_hs_oBank 0

const unsigned char bkg_hs_o[] =
{
  0x05,0x0B,0x0C,0x25,0x25,0x06,0x0D,0x0E,0x0F,0x10
};

/* End of BKG_HS_OPT.C */
