/*

 BKG_SINGLE_CARDS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : background_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bkg_single_cards_h_INCLUDE
#define __bkg_single_cards_h_INCLUDE

#define bkg_single_cardsWidth 4
#define bkg_single_cardsHeight 5
#define bkg_single_cardsBank 0

// #define bkg_single_cards bkg_1_cards
extern const unsigned char bkg_1_cards[];

#endif

/* End of BKG_SINGLE_CARDS.H */
