/*

 BKG_PUSHGM.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 3
   Tile set      : C:\Users\alexa\OneDrive\Desktop\C Files\GB\blackjack_gb_game\res_\gbr_files\bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_pushWidth 6
#define bkg_pushHeight 3
#define bkg_pushBank 0

const unsigned char bkg_push[] =
{
  0x5A,0x5D,0x5D,0x5D,0x5D,0x5F,0x5B,0x19,0x1E,0x1C,
  0x11,0x60,0x5C,0x5E,0x5E,0x5E,0x5E,0x61
};

/* End of BKG_PUSHGM.C */
