/*

 BKG_GAME_INFO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 6
   Tile set      : C:\Users\alexa\OneDrive\Desktop\C Files\GB\blackjack_gb_game\res_\gbr_files\bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bkg_game_info_h_INCLUDE
#define __bkg_game_info_h_INCLUDE

#define bkg_gm_infoWidth 12
#define bkg_gm_infoHeight 6
#define bkg_gm_infoBank 0

extern const unsigned char bkg_gm_info[];

#endif

/* End of BKG_GAME_INFO.H */
