/*

 CASH_WINDOW.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 14 x 1
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __cash_window_h_INCLUDE
#define __cash_window_h_INCLUDE

#define bkg_cash_betWidth 14
#define bkg_cash_betHeight 1
#define bkg_cash_betBank 0

extern const unsigned char bkg_cash_bet[];

#endif

/* End of CASH_WINDOW.H */
