/*

 CHANGE_BET.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 5
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __change_bet_h_INCLUDE
#define __change_bet_h_INCLUDE

#define bkg_chg_betWidth 8
#define bkg_chg_betHeight 5
#define bkg_chg_betBank 0

extern const unsigned char bkg_chg_bet[];

#endif

/* End of CHANGE_BET.H */
