/*

 CHIPS_WIN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 3
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __chips_win_h_INCLUDE
#define __chips_win_h_INCLUDE

#define chipsWidth 18
#define chipsHeight 3
#define chipsBank 0

extern const unsigned char chips[];

#endif

/* End of CHIPS_WIN.H */
