/*

 END_AMT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 17 x 3
   Tile set      : bkg_tiles_opt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __end_amt_h_INCLUDE
#define __end_amt_h_INCLUDE

#define ending_amtWidth 17
#define ending_amtHeight 3
#define ending_amtBank 0

extern const unsigned char ending_amt[];

#endif

/* End of END_AMT.H */
