/*

 HOLE_CARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __hole_card_h_INCLUDE
#define __hole_card_h_INCLUDE

#define holeWidth 1
#define holeHeight 5
#define holeBank 0

extern const unsigned char hole[];

#endif

/* End of HOLE_CARD.H */
