/*

 HOLE_CARD.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define holeWidth 1
#define holeHeight 5
#define holeBank 0

const unsigned char hole[] =
{
  0x33,0x34,0x34,0x34,0x35
};

/* End of HOLE_CARD.C */
