/*

 PRESS_TO_CHG_BET.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 17 x 4
   Tile set      : bkg_tiles_opt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __press_to_chg_bet_h_INCLUDE
#define __press_to_chg_bet_h_INCLUDE

#define dwn_to_chg_betWidth 17
#define dwn_to_chg_betHeight 4
#define dwn_to_chg_betBank 0

extern const unsigned char dwn_to_chg_bet[];

#endif

/* End of PRESS_TO_CHG_BET.H */
