/*

 STARTING_AMT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 17 x 4
   Tile set      : bkg_tiles_opt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __starting_amt_h_INCLUDE
#define __starting_amt_h_INCLUDE

#define starting_amtWidth 17
#define starting_amtHeight 4
#define starting_amtBank 0

extern const unsigned char starting_amt[];

#endif

/* End of STARTING_AMT.H */
