/*

 TABLE_CHANGE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 25
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __table_change_h_INCLUDE
#define __table_change_h_INCLUDE

#define bkg_tab_cWidth 20
#define bkg_tab_cHeight 25
#define bkg_tab_cBank 0

extern const unsigned char bkg_tab_c[];

#endif

/* End of TABLE_CHANGE.H */
