/*

 FIRST_CARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 5
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __first_card_h_INCLUDE
#define __first_card_h_INCLUDE

#define bkg_score_w_card1Width 1
#define bkg_score_w_card1Height 5
#define bkg_score_w_card1Bank 0

extern const unsigned char bkg_first_card[];

#endif

/* End of FIRST_CARD.H */
