/*

 INSURANCE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 5
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __insurance_h_INCLUDE
#define __insurance_h_INCLUDE

#define bkg_insWidth 12
#define bkg_insHeight 5
#define bkg_insBank 0

extern const unsigned char bkg_ins[];

#endif

/* End of INSURANCE.H */
