/*

 NEXT_CARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __next_card_h_INCLUDE
#define __next_card_h_INCLUDE

#define bkg_next_cardWidth 4
#define bkg_next_cardHeight 5
#define bkg_next_cardBank 0

extern const unsigned char bkg_next_card[];

#endif

/* End of NEXT_CARD.H */
