/*

 PUSH.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 6 x 3
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __push_h_INCLUDE
#define __push_h_INCLUDE

#define bkg_pushWidth 6
#define bkg_pushHeight 3
#define bkg_pushBank 0

extern const unsigned char bkg_push[];

#endif

/* End of PUSH.H */
