/*

 SURRENDERED.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 13 x 3
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __surrendered_h_INCLUDE
#define __surrendered_h_INCLUDE

#define bkg_surWidth 13
#define bkg_surHeight 3
#define bkg_surBank 0

extern const unsigned char bkg_sur[];

#endif

/* End of SURRENDERED.H */
