/*

 BKG_SM_BET.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 3
   Tile set      : background_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_winWidth 9
#define bkg_winHeight 3
#define bkg_winBank 0

extern unsigned char bkg_win[];

/* End of BKG_SM_BET.H */
