/*

 BKG_5_CARDS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 5
   Tile set      : background_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bkg_5_cards_h_INCLUDE
#define __bkg_5_cards_h_INCLUDE

#define bkg_5_cardsWidth 8
#define bkg_5_cardsHeight 5
#define bkg_5_cardsBank 0

extern const unsigned char bkg_5_cards[];

#endif

/* End of BKG_5_CARDS.H */
