/*

 BKG_6_CARDS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 9 x 5
   Tile set      : background_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bkg_6_cards_h_INCLUDE
#define __bkg_6_cards_h_INCLUDE

#define bkg_6_cardsWidth 9
#define bkg_6_cardsHeight 5
#define bkg_6_cardsBank 0

extern const unsigned char bkg_6_cards[];

#endif

/* End of BKG_6_CARDS.H */
