/*

 BKG_SC_C1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : background_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __bkg_sc_c1_h_INCLUDE
#define __bkg_sc_c1_h_INCLUDE

#define bkg_score_w_card1Width 4
#define bkg_score_w_card1Height 5
#define bkg_score_w_card1Bank 0

extern const unsigned char bkg_score_w_card1[];

#endif

/* End of BKG_SC_C1.H */
