/*

 BKG_LOSE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 3
   Tile set      : background_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_loserWidth 10
#define bkg_loserHeight 3
#define bkg_loserBank 0

const unsigned char bkg_loser[] =
{
  0x3A,0x3B,0x3B,0x3B,0x3B,0x3B,0x3B,0x3B,0x3B,0x3C,
  0x41,0x68,0x5E,0x64,0x00,0x5B,0x5E,0x62,0x54,0x3D,
  0x3E,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0x3F
};

/* End of BKG_LOSE.C */
