/*

 NEXT_CARD.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 5
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bkg_next_cardWidth 4
#define bkg_next_cardHeight 5
#define bkg_next_cardBank 0

const unsigned char bkg_next_card[] =
{
  0x39,0x3B,0x3B,0x3D,0x37,0x2F,0x2F,0x3E,0x37,0x2F,
  0x2F,0x3E,0x37,0x2F,0x2F,0x3E,0x3A,0x3C,0x3C,0x3F
};

/* End of NEXT_CARD.C */
