/*

 TABLE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __table_h_INCLUDE
#define __table_h_INCLUDE

#define bkg_tabWidth 20
#define bkg_tabHeight 18
#define bkg_tabBank 0

extern const unsigned char bkg_tab[];

#endif

/* End of TABLE.H */
