/*

 YOU_WIN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 3
   Tile set      : bkg_tiles_reformated.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __you_win_h_INCLUDE
#define __you_win_h_INCLUDE

#define bkg_winnerWidth 10
#define bkg_winnerHeight 3
#define bkg_winnerBank 0

extern const unsigned char bkg_winner[];

#endif

/* End of YOU_WIN.H */
